###################################################
#                                                 #
# Example config for a consumer that reads from a #
# topic and loads the records into a database     #
#                                                 #
###################################################

kafka.common.bootstrap.servers=${BOOTSTRAP_SERVERS}
kafka.common.schema.registry.url=${SCHEMA_REGISTRY}

client.type=${CLIENT_TYPE}

kafka.common.topic=${KAFKA_TOPIC}


kafka.common.ssl.key.password=${KEY_PASSWORD}
kafka.common.ssl.truststore.location=${TRUSTSTORE_LOCATION}
kafka.common.ssl.truststore.password=${TRUSTSTORE_PASSOWRD}
kafka.common.ssl.keystore.location=${KEYSTORE_LOCATION}
kafka.common.ssl.keystore.password=${KEYSTORE_PASSWORD}
kafka.consumer.include.metadata=${METADATA}
##Change this for every run
kafka.consumer.auto.offset.reset=${OFFSET_RESET}
kafka.consumer.exit.on.finish=${EXIT_FINISH}
kafka.consumer.group.id=${GROUP_ID}
kafka.consumer.max.poll.records=${FETCH_RECORDS}
kafka.consumer.max.partition.fetch.bytes=${FETCH_BYTES}
kafka.consumer.offset=${OFFSET}
kafka.consumer.value.deserializer=${DESERIALIZER}





#GCP
google.bigquery.dataset=${DATASET}
google.project.id=${PROJECT_ID}
google.bigquery.table=${TABLE_NAME}
google.application.credentials=${CREDENTIALS_FILE}
gcs.load.option=${LOAD_OPTION}
google.storage.bucket.name=${BUCKET_NAME}
google.storage.folder.name=${FOLDER_NAME}

