###################################################
#                                                 #
# Example config for a producer that reads from a #
# topic and loads the records into a database     #
#                                                 #
###################################################


kafka.common.bootstrap.servers=${BOOTSTRAP_SERVERS}
kafka.common.schema.registry.url=${SCHEMA_REGISTRY}

client.type=PRODUCER_DB_PLAIN

kafka.common.topic=dat.edfkometa.kom-tabela-dokumenty-np.incoming.avro

kafka.common.ssl.key.password=${KEY_PASSWORD}
kafka.common.ssl.truststore.location=${TRUSTSTORE_LOCATION}
kafka.common.ssl.truststore.password=${TRUSTSTORE_PASSWORD}
kafka.common.ssl.keystore.location=${KEYSTORE_LOCATION}
kafka.common.ssl.keystore.password=${KEYSTORE_PASSWORD}


db.type=postgresql

db.username=${DB_USERNAME}
db.password=${DB_PASSWORD}
db.host=${DB_HOST}
db.port=${DB_PORT}
db.table=tabela_dokumenty
db.name=${DB_NAME}
db.fetch=500
db.schema=public

