###################################################
#                                                 #
# Example config for a producer that reads from a #
# topic and loads the records into a database     #
#                                                 #
###################################################


kafka.common.bootstrap.servers=${BOOTSTRAP_SERVERS}
kafka.common.schema.registry.url=${SCHEMA_REGISTRY}

client.type=${CLIENT_TYPE}

kafka.common.topic=${KAFKA_TOPIC}

kafka.common.ssl.key.password=${KEY_PASSWORD}
kafka.common.ssl.truststore.location=${TRUSTSTORE_LOCATION}
kafka.common.ssl.truststore.password=${TRUSTSTORE_PASSWORD}
kafka.common.ssl.keystore.location=${KEYSTORE_LOCATION}
kafka.common.ssl.keystore.password=${KEYSTORE_PASSWORD}


db.type=${DB_TYPE}

db.username=${DB_USERNAME}
db.password=${DB_PASSWORD}
db.host=${DB_HOST}
db.port=${DB_PORT}
db.table=${DB_TABLE}
db.name=${DB_NAME}
db.fetch=${DB_FETCH}

# if applicable
db.schema=${DB_SCHEMA}

